title: Emus dude
author: G-raff
email: griffen@griffen.com
description: > # this means to ignore newlines until "baseurl:"
  There isn't enough talk about the great emu war. This blog is here to fix that.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
